### PR TITLE
refactoring of gpt_params_parse with correct validateParams function

### PR DESCRIPTION
**Pull request by maddes8cht**
In falcon_common.cpp, we have this nice `gpt_params_parse` function that adds parameter validations everywhere. However, I discovered that this validation only works for the last parameter of the command line. Otherwise, checking if a parameter has an argument always gives a positive result because the validation only checks if there are more arguments on the command line, which is true if there are more parameters on the command line.

Examples:

* `falcon_main -m /path/to/model.bin -t 5` works as expected.
* `falcon_main -m /path/to/model.bin -t` accordingly does not and prints an error message, as desired.
* `falcon_main -t -m /path/to/model.bin` should be equivalent to the above command, but the validation accepts `-m` as an argument of `-t`, leading to unexpected behavior, and the program aborts without an error message.
This PR corrects this behavior by introducing a modification in the `validateParams` function, which now explicitly checks whether the requested argument after a parameter is not another parameter. As a result, the code in the `gpt_params_parse` function becomes considerably shorter.

Please review and consider merging.

### CODE REVIEW

**Comment by cmp-nct** [comment]
It looks like there are some conflicts preventing the merge but sounds like a good addition.
I'll take a look as soon as I can.

**Review by maddes8cht — COMMENTED** [review]
it was simply the added "open-assistant-v1" line

**Comment by maddes8cht** [comment]
While on the road it struck me that current implementation of validateParams will prevent any negative number as parameter arguments, so don't merge until that is resolved. Will take some hours till i'm back on a PC.

**Comment by maddes8cht** [comment]
I have fixed the problem with the negative arguments. It looks good for me now.
The merge conflict came from the added FINETUNE_OPENASSIST_V1;
As far as I can see, my version is now identical to the conflict except for whitespace. Since the conflict version is in conflict with the surrounding formatting and my formatting is in agreement with it, I propose to adopt my version.

**Comment by maddes8cht** [comment]
It's still a very rough 'validation' that still can be easily tricked into an undetermined state, leading to a silent crash of the program. So there is not even a check wheather an argument should be a number or a string.
I don't know if we want that level of validation (there's a reason why it hasn't happened yet, but there's also a reason why these validations exist: having meaningful error messages helps in finding what one did wrong, and not having them can consume  lot of time finding out).

And as this meets my current skills-level in c++,  I would be happy to be available for such a task if it is appreciated :)

**Comment by cmp-nct** [comment]
Did you verify all the important parameters go through the validation ?
Like vram reserved MB (positive and negative), gpu tensor split, stop words, multiple prompts, file input

**Pull request closed without merging**
