### PR TITLE
AMD GPU Support

### PR DESCRIPTION
**Pull request by AlkindiX**
[Screencast from 06-17-2023 04:39:17 PM.webm](https://github.com/cmp-nct/ggllm.cpp/assets/6407635/d8a3fdcb-bb98-4883-800b-a889fe5c9933)

[https://gist.github.com/AlkindiX/9c54d1155ba72415f3b585e26c9df6b3](https://gist.github.com/AlkindiX/9c54d1155ba72415f3b585e26c9df6b3)

### CODE REVIEW

**Comment by cmp-nct** [comment]
Hi, that will need a deeper check
I'm quite happy to see that you've a V3 ggml quantized binary running, I was under the impression that quantization is bugged.
Did you just convert it into Q5 and it worked ! 

Regarding AMD/CUDA: I might be mistaken but I think your example runs 100% on CPU, we currently have no CUDA offload set up (all CPU backend until fixed) and you did not use the -ngl parameter (which would offload the layers to GPU)
The inference speed is 2x faster than mine on fp16, which would probably fall in line with the Q5 speedup

**Comment by AlkindiX** [comment]
Hi @cmp-nct 

I tried to use the -ngl argument, but it threw a segmentation fault. The purpose of this argument was to ensure that only the GPU backend was used, without any CPU assertions afterward (which never happen). Upon reviewing the comments, I found mentions of two missing CUDA implementations: the GLEU and repeat kernels in lamma.cpp. I can confirm that these implementations are indeed missing. Additionally, I had fun experimenting with the HIP for AMD, which resulted in running entirely on the CPU.

Could you please explain why my GPU usage is at 100%? Does the implementation allow for split computation on the GPU and CPU using shared memory?

By the way, I downloaded the [gpt4all-falcon](https://huggingface.co/nomic-ai/gpt4all-falcon) model. I used ./falcon_convert.py, but it didn't work initially as it was pointing to an empty directory. To resolve this, I copied the symbolic linked PyTorch model files to that directory, and it started working. Two files were generated: model-f32 and model-f16. I tried using the model-f16, but it failed, and its size is only 1% of the model size. However, the other file was successful.

Furthermore, when I tried to use the falcon_convert and falcon_main from the examples, I encountered issues with the compilation. It couldn't find the falcon_common file, if I recall correctly.

**Comment by AlkindiX** [comment]
Have you considered looking up the PyTorch/TensorFlow implementation of GLEU and repeat, or are they different from what you mentioned earlier?

**Comment by cmp-nct** [comment]
We have a new branch since yesterday "cuda-integration", it has a first mat-mul integration for some of the weights working (speedup up to 3 times over CPU only). 
You can try that in combination with the AMD cuda but it's a bit early. The cuda integration will change a lot.

For models you should start with the official falcon model first, use the conversion and quantization tools supplied in this repository, not others as they can differ.

And yes, GELU and repeat2 are not available at the moment, but we are a few steps from full GPU support. For now I'm happy if the partial GPU offload works flawless in all instances.

**Pull request closed without merging**
